# Generated by Django 5.0.4 on 2024-04-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='dialog_id',
            new_name='dialogue_id',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='is_added',
        ),
        migrations.RemoveField(
            model_name='message',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='dialogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.dialogue'),
            preserve_default=False,
        ),
    ]
