# Generated by Django 5.0.4 on 2024-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dialogue_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='dialogue_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
