# Generated by Django 5.0.4 on 2024-04-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
